# golangci-lint configuration for Go 1.23+ (2025)
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  go: '1.23'

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    # Enabled by default
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter
    - unused        # Check for unused constants, variables, functions

    # Additional recommended linters
    - gofmt         # Check code formatting
    - goimports     # Check import formatting
    - revive        # Fast, configurable, extensible linter
    - gosec         # Security problems
    - misspell      # Spelling mistakes
    - unconvert     # Unnecessary type conversions
    - unparam       # Unused function parameters
    - gocyclo       # Cyclomatic complexity
    - gocritic      # Comprehensive linter
    - gocognit      # Cognitive complexity
    - dupl          # Code cloning detection
    - godot         # Comment periods
    - whitespace    # Whitespace issues
    - wsl           # Whitespace linter
    - errorlint     # Error wrapping
    - exhaustive    # Exhaustiveness of enum switch
    - goconst       # Repeated strings to constants
    - mnd           # Magic numbers
    - nestif        # Deep nesting
    - prealloc      # Slice preallocation
    - predeclared   # Shadowed predeclared identifiers
    - nolintlint    # Nolint directive issues
    - stylecheck    # Style issues
    - thelper       # Test helper detection
    - tparallel     # Parallel test detection
    - wastedassign  # Wasted assignments

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/yourusername/init-golang-template

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # Audit errors not checked (covered by errcheck)

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true

  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '10'
      - '100'
      - '1000'

  misspell:
    locale: US
    ignore-words:
      - cancelled

  nestif:
    min-complexity: 4

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
      - hugeParam

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022", "-ST1023"]
    dot-import-whitelist:
      - fmt
    http-status-code-whitelist: ["200", "400", "404", "500"]
    # Disabled checks:
    # ST1000: Package comment
    # ST1003: Naming conventions
    # ST1016: Receiver naming
    # ST1020: Comment should end in a period
    # ST1021: Comment should not start with the name of the declaration
    # ST1022: Comment should have a leading space
    # ST1023: Comment should start with a capital letter

  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - mnd

    # Exclude known false positives
    - path: internal/
      text: "exported .* should have comment"
      linters:
        - revive

    # Disable linters that are annoying in large refactors
    - path: internal/
      linters:
        - gocritic

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false

severity:
  default-severity: error
  rules:
    - linters:
        - dupl
      severity: info
