environment: development

server:
  host: localhost
  port: 8080

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  database: myapp
  ssl_mode: disable

log:
  level: info
  format: json
